name: release-go

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build
        run: |
          go build -o dist/iso-downloader ./cmd/iso-downloader
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso-downloader-go-linux
          path: dist/iso-downloader

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: iso-downloader-go-linux
          path: dist
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Create tag and release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          files: dist/iso-downloader
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}