name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt pyinstaller build
      - name: Build binary
        run: bash scripts/build.pyinstaller.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso-downloader-linux
          path: dist/iso-downloader

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: iso-downloader-linux
          path: dist
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/iso-downloader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


